# Generated by Django 5.1 on 2024-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="target",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="control",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
